# Edit this file by hand. Using `pnpm config` reformats the file and removes all comments.

packages:
  - "apps/**"
  - "components/**"
  - "packages/*"
  - "proprietary/*"

# Configure pnpm so peer dependencies are automatically installed.
autoInstallPeers: true

# Configure pnpm so that it will not install any package that claims to not be compatible with the current Node.js
# version.
engineStrict: true

# Configure pnpm so it only installs package versions that have been published on the npm registry for at least 24 hours
# (1440 minutes). This helps mitigate the risk of supply chain attacks by avoiding newly published, potentially
# malicious versions. Keep this in sync with npm-check-updates's `cooldown` configuration.
minimumReleaseAge: 1440

# Make an exception for trusted packages, notably our own
minimumReleaseAgeExclude:
  - "@amsterdam/*"
  - "@gemeente-denhaag/*"
  - "@gemeente-rotterdam/*"
  - "@nl-design-system/*"
  - "@nl-design-system-candidate/*"
  - "@nl-design-system-community/*"
  - "@nl-design-system-unstable/*"
  - "@nl-rvo/*"
  - "@rijkshuisstijl-community/*"
  - "@utrecht/*"
  - "@next/*"
  - "next"
  - "eslint-config-next@15.5.9"
  - "react@19.2.3"
  - "react-dom@19.2.3"
  - "@isaacs/brace-expansion"

# Configure pnpm to save exact version numbers (not including ^ or ~) in package.json. Lock dependencies to specific
# versions to ensure reproducible installs and prevent automatic upgrades to newer minor or patch releases.
saveExact: true
savePrefix: ""

overrides:
  '@isaacs/brace-expansion@<=5.0.0': '>=5.0.1'
  axios@>=1.0.0 <1.12.0: '>=1.12.0'
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
  braces@<3.0.3: '>=3.0.3'
  cross-spawn@<6.0.6: '>=6.0.6'
  diff@>=5.0.0 <5.2.2: '>=5.2.2'
  expr-eval-fork@<=3.0.0: '>=3.0.1'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  glob@>=11.0.0 <11.1.0: '>=11.1.0'
  hono@<4.11.4: '>=4.11.4'
  hono@<4.11.7: '>=4.11.7'
  js-yaml@<3.14.2: '>=3.14.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  locutus@>=2.0.12 <2.0.39: '>=2.0.39'
  lodash-es@>=4.0.0 <=4.17.22: '>=4.17.23'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  micromatch@<4.0.8: '>=4.0.8'
  next@>=10.0.0 <15.5.10: '>=15.5.10'
  next@>=15.0.0-canary.0 <15.6.0-canary.61: '>=15.6.0-canary.61'
  next@>=15.5.1-canary.0 <15.5.10: '>=15.5.10'
  node-forge@<1.3.2: '>=1.3.2'
  on-headers@<1.1.0: '>=1.1.0'
  playwright@<1.55.1: '>=1.55.1'
  preact@>=10.27.0 <10.27.3: '>=10.27.3'
  prismjs@<1.30.0: '>=1.30.0'
  qs@<6.14.1: '>=6.14.1'
  storybook@>=9.0.0 <9.1.17: '>=9.1.17'
  tar@<7.5.7: '>=7.5.7'
  tar@<=7.5.2: '>=7.5.3'
  tar@<=7.5.3: '>=7.5.4'
  tmp@<=0.2.3: '>=0.2.4'
  vite@>=6.0.0 <=6.3.5: '>=6.3.6'
  vite@>=6.0.0 <=6.4.0: '>=6.4.1'

# Configure pnpm to not fail when there are missing or invalid peer dependencies in the tree.
strictPeerDependencies: false
