title: "Rijkshuisstijl interpretatie "
body:
  - type: markdown
    attributes:
      value: |
        # {Naam onderdeel, zoals: Button - Rijkshuisstijl keuzes}
        _Laatste update: {datum, zoals: 14-4-2025}_  

        ## Keuzes en overwegingen

        <!---
        Noteer hier per onderwerp welke ontwerpkeuze is gemaakt, waarom deze keuze is gemaakt, én op basis van welke informatie of bron (zoals onderzoek, huisstijl of WCAG-richtlijnen).
        Gebruik de onderstaande structuur en voeg onderwerpen toe die relevant zijn, zoals kleurgebruik, focusstijl of afgeronde hoeken. Combineer de keuze, de reden en eventuele onderbouwing in één korte alinea per punt. 
        -->

  - type: markdown
    attributes:
      value: |
        ### Kleurgebruik
        {Welke kleur is gebruikt? Voldoet deze aan WCAG? Afwijking toegepast?}

  - type: markdown
    attributes:
      value: |
        ### Typografie
        {Welke tekstgrootte is gekozen? Valt dit onder “grote tekst”? Is het schaalbaar?}

  - type: markdown
    attributes:
      value: |
        ### Toegankelijkheid
        {Hoe is met contrast, focus, leesbaarheid etc. rekening gehouden?}

  - type: markdown
    attributes:
      value: |
        ### Interactie/gedrag
        {Wat gebeurt er bij hover/focus/active? Afwijkingen van huisstijl?}

  - type: markdown
    attributes:
      value: |
        ### Afgeronde hoeken
        {Wat is de border-radius (bijv. 4px, 8px)? Komt dit overeen met huisstijl of tokens? Waarom is voor deze vorm gekozen? Heeft het invloed op herkenbaarheid of gebruiksvriendelijkheid?}

  - type: markdown
    attributes:
      value: |
        ### Uitlijning en spacing
        {Welke paddings zijn gebruikt? Hoe is gekozen voor uitlijning (links, gecentreerd)? Wat is de visuele of functionele reden hiervoor? Zijn hier tokens voor gebruikt?}

  - type: markdown
    attributes:
      value: |
        <!---
        Voeg hier gerust extra regels toe voor onderwerpen zoals: iconen, font-weight, padding etc.
        -->

  - type: markdown
    attributes:
      value: |
        ## Vragen of discussiepunten

        - [Bijvoorbeeld: Wat zijn ervaringen bij andere organisaties met deze component?]
        - [Bijvoorbeeld: Is deze keuze herkenbaar of juist afwijkend voor jullie praktijk?]
        - [Bijvoorbeeld: Hoe kunnen we deze keuze het beste borgen in de richtlijnen of design tokens?]

  - type: markdown
    attributes:
      value: |
        ## Handige links

        - **Figma component:** [Link naar Figma]  
        - **Rijkshuisstijl website:** [Link naar betreffende pagina]  
        - **WCAG-richtlijnen (indien van toepassing):** [Bijv. Contrast – WCAG 1.4.3](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html)  
        - **Design tokens:** `[noem hier relevante tokens uit Token Studio]`
        - ...
