title: "{Naam van het onderdeel}"
body:
  - type: textarea
    id: rijkshuisstijl-interpretatie
    attributes:
      label: Rijkshuisstijl interpretatie
      value: |
        In deze discussie verzamelen, bespreken en documenteren we de ontwerpkeuzes voor dit onderdeel binnen de nieuwe Rijkshuisstijl. Het doel is om meer uniformiteit te creëren tussen verschillende Rijksoverheidswebsites en gezamenlijk tot één ontwerp te komen. Zie de [overkoepelende richtlijnen[(https://github.com/nl-design-system/rijkshuisstijl-community/discussions/1505) en denk gerust mee!

        _Voeg hier een visuele referentie toe, zodat in één oogopslag duidelijk is over welk component, patroon, template of onderdeel het gaat._

        ## Relevante links

        _Voeg hier gerust extra handige links toe, of laat er één of meerdere weg als ze niet van toepassing zijn._

        - [NL Design System GitHub - Component Discussion](https://github.com/orgs/nl-design-system/discussions/categories/component-suggestions)
        - [NL Design System GitHub - Backlog](https://github.com/nl-design-system/backlog/issues/101)
        - [Figma component](link-naar-figma)
        - [Rijkshuisstijl richtlijnen](link-naar-richtlijnen)

        ## Gevonden informatie

        _Beschrijf welke informatie je hebt gevonden over dit onderdeel en link ernaar indien mogelijk._

        ## Varianten of types

        _Leg vast welke keuze is gemaakt, waarom en op basis van welke bron (bijvoorbeeld onderzoek, huisstijl of WCAG). Laat dit onderwerp weg als het niet van toepassing is. Denk aan: welke varianten zijn er (bijvoorbeeld Primary Action, Secondary Action)? Welke types zijn er (bijvoorbeeld Success, Error, Warning)?_

        ## Kleur

        _Leg vast welke keuze is gemaakt, waarom en op basis van welke bron. Laat dit onderwerp weg als het niet van toepassing is. Denk aan: welke kleur is gebruikt? Voldoet deze aan WCAG? Is er een afwijking toegepast?_

        ## Typografie

        _Leg vast welke keuze is gemaakt, waarom en op basis van welke bron. Laat dit onderwerp weg als het niet van toepassing is. Denk aan: welke font-size en font-weight zijn gekozen?_

        ## Border
        
        _Leg vast welke keuze is gemaakt, waarom en op basis van welke bron. Laat dit onderwerp weg als het niet van toepassing is. Denk aan: wat is de border-width of border-radius (bijvoorbeeld 4px, 8px)? Komt dit overeen met de huisstijl of tokens? Heeft het invloed op herkenbaarheid of gebruiksvriendelijkheid?_
        
        ## Uitlijning en spacing
        
        _Leg vast welke keuze is gemaakt, waarom en op basis van welke bron. Laat dit onderwerp weg als het niet van toepassing is. Denk aan: welke paddings zijn gebruikt? Hoe is de uitlijning bepaald (links, gecentreerd)? Wat is de visuele of functionele reden hiervoor? Zijn er tokens gebruikt?_
        
        ## Styling van states
        
        _Leg vast welke keuze is gemaakt, waarom en op basis van welke bron. Laat dit onderwerp weg als het niet van toepassing is. Denk aan: hoe ziet de styling eruit voor active, hover en focus-visible? Voldoet deze aan WCAG?_
        
        ## {naam-onderwerp}
        
        _Voeg hier gerust extra onderwerpen toe, zoals iconen, rounded-corner of andere details._
        
        ## Vragen of discussiepunten
        
        _Noteer hier openstaande vragen of beslissingen die nog besproken moeten worden._
