export const allComponentsData = [
  {
    id: 'accordion',
    title: 'Accordion',
    heading: 'Accordion',
    description: 'Secties met de mogelijkheid om gerelateerde content te tonen en weer te verbergen.',
    href: '#',
    metadata: '',
    status: 'Community',
    frameworks: ['React', 'CSS'],
  },
  {
    id: 'action-group',
    title: 'Action Group',
    heading: 'Action Group',
    description: 'Groepeert één of meer gerelateerde acties en verzorgt de lay-out van de content.',
    href: '#',
    metadata: '',
    status: 'Help Wanted',
    frameworks: ['React', 'Web Components'],
  },
  {
    id: 'alert',
    title: 'Alert',
    heading: 'Alert',
    description: 'Belangrijk bericht dat informeert over de huidige activiteit van de gebruiker.',
    href: '#',
    metadata: '',
    status: 'Community',
    frameworks: ['CSS', 'Angular', 'Twig'],
  },
  {
    id: 'blockquote',
    title: 'Blockquote',
    heading: 'Blockquote',
    description: 'Toont een citaat dat afwijkt van de hoofdtekst.',
    href: '#',
    metadata: '',
    status: 'Community',
    frameworks: ['CSS'],
  },
  {
    id: 'breadcrumb-navigation',
    title: 'Breadcrumb Navigation',
    heading: 'Breadcrumb Navigation',
    description:
      'Toont de locatie van de pagina binnen de hiërarchie van een website en biedt de mogelijkheid om tussen niveaus te navigeren.',
    href: '#',
    metadata: '',
    status: 'Community',
    frameworks: ['React', 'Angular', 'CSS'],
  },
  {
    id: 'button',
    title: 'Button',
    heading: 'Button',
    description: 'Biedt de mogelijkheid om een actie uit te voeren.',
    href: '#',
    metadata: '',
    status: 'Community',
    frameworks: ['React', 'CSS', 'Web Components', 'Angular', 'Twig'],
  },
  {
    id: 'checkbox-group',
    title: 'Checkbox Group',
    heading: 'Checkbox Group',
    description: 'Biedt de mogelijkheid om geen, één of meerdere opties te selecteren uit een lijst.',
    href: '#',
    metadata: '',
    status: 'Help Wanted',
    frameworks: ['React', 'Angular'],
  },
  {
    id: 'card-as-link',
    title: 'Card as Link',
    heading: 'Card as Link',
    description: 'Korte sectie die als geheel een link is naar een gerelateerde pagina.',
    href: '#',
    metadata: '',
    status: 'Help Wanted',
    frameworks: ['CSS', 'Twig'],
  },
  {
    id: 'checkbox',
    title: 'Checkbox',
    heading: 'Checkbox',
    description: 'Toont meta-informatie over een zaak en biedt de mogelijkheid hier naartoe te navigeren.', // Description seems off, copied from your code.
    href: '#',
    metadata: '',
    status: 'Help Wanted',
    frameworks: ['React', 'Web Components'],
  },
  {
    id: 'dot-badge',
    title: 'Dot Badge',
    heading: 'Dot Badge',
    description: 'Stip bij een Link of Button die zonder zichtbaar label de aandacht trekt bij een statuswijziging.',
    href: '#',
    metadata: '',
    status: 'Help Wanted',
    frameworks: ['CSS'],
  },
  // Add more components if you have more than 10
];
