import { Component, Input } from '@angular/core';
import { provideTablerIcons, TablerIconComponent } from 'angular-tabler-icons';
import * as TablerIcons from 'angular-tabler-icons/icons';
import { RHCIconID } from './RHCIconIDs';

@Component({
  selector: 'rhc-icon',
  imports: [TablerIconComponent],
  templateUrl: './icon.component.html',
  providers: [provideTablerIcons(TablerIcons)],
  styleUrl: './icon.component.css',
})
export class IconComponent {
  @Input({ required: false }) icon?: string;
  static iconSet: Partial<Record<RHCIconID, string>> = {
    activiteit: 'calendar-check',
    'agile-werken': 'arrow-iteration',
    'alert-circle': 'alert-circle',
    'api-inrichting': 'api',
    'arrows-sort': 'arrows-sort',
    audio: 'volume',
    bel: 'bell',
    bewerken: 'edit',
    blog: 'file-pencil',
    briefcase: 'briefcase',
    car: 'car',
    'circle-check': 'circle-check',
    'chevron-right': 'chevron-right',
    comment: 'message-dots',
    communicatie: 'bubble',
    delen: 'share',
    'delta-naar-links': 'caret-left',
    'delta-naar-rechts': 'caret-right',
    'delta-omhoog': 'caret-up',
    'delta-omlaag': 'caret-down',
    'diagonale-pijl': 'arrow-up-right',
    downloaden: 'download',
    inbox: 'inbox',
    'currency-euro': 'currency-euro',
    'externe-link': 'external-link',
    favoriet: 'heart',
    'foto-vergroten': 'arrows-diagonal',
    gegevensuitwisseling: 'transfer',
    'geluid-aan': 'volume',
    'geluid-uit': 'volume-off',
    'haakse-pijl': 'corner-left-up',
    hashtag: 'hash',
    home: 'home',
    info: 'info-small',
    'info-circle': 'info-circle',
    'info-square': 'info-square',
    inloggen: 'login-2',
    instellingen: 'settings',
    'interne-link': 'link',
    kalender: 'calendar-check',
    klok: 'clock',
    kruis: 'x',
    'let-op-met-loep': 'alert-circle',
    'let-op': 'alert-triangle',
    locatiemarker: 'map-pin',
    mail: 'mail',
    meer: 'dots-vertical',
    menu: 'menu-2',
    nieuws: 'news',
    paperclip: 'paperclip',
    'permanent-beta': 'backhoe',
    'pijl-naar-rechts': 'arrow-narrow-right',
    'pijl-naar-rechtsboven': 'arrow-up-right',
    'pijl-omhoog': 'arrow-narrow-up',
    'pijl-omlaag': 'arrow-narrow-down',
    plus: 'plus',
    printer: 'printer',
    publicatie: 'file',
    'rechte-pijl': 'arrow-narrow-up',
    refresh: 'reload',
    rss: 'rss',
    save: 'device-floppy',
    school: 'school',
    'secure-link': 'lock',
    smartphone: 'device-mobile',
    'sort-ascending': 'sort-ascending',
    'sort-descending': 'sort-descending',
    tegelweergave: 'grid-dots',
    telefoon: 'phone',
    terug: 'arrow-narrow-left',
    toegankelijkheid: 'eye',
    toelichting: 'square',
    'uit-aanknop': 'power',
    upload: 'upload',
    user: 'user',
    versleutelen: 'cloud-lock',
    verwijderen: 'trash',
    verzenden: 'send',
    video: 'player-play',
    vinkje: 'check',
    vraagteken: 'question-mark',
    zoek: 'search',
  };
  computedIconRender = () => IconComponent.iconSet[this.icon as RHCIconID] || '';

  static iconSetKeys(): RHCIconID[] {
    return Object.keys(IconComponent.iconSet) as RHCIconID[];
  }
}
