import {
  IconAlertCircle,
  IconAlertTriangle,
  IconApi,
  IconArrowIteration,
  IconArrowNarrowDown,
  IconArrowNarrowLeft,
  IconArrowNarrowRight,
  IconArrowNarrowUp,
  IconArrowsDiagonal,
  IconArrowUpRight,
  IconBackhoe,
  IconBell,
  IconBubble,
  IconCalendarCheck,
  IconCaretDown,
  IconCaretLeft,
  IconCaretRight,
  IconCaretUp,
  IconCheck,
  IconClock,
  IconCloudLock,
  IconCornerLeftUp,
  IconDeviceFloppy,
  IconDeviceMobile,
  IconDotsVertical,
  IconDownload,
  IconEdit,
  IconExternalLink,
  IconEye,
  IconFile,
  IconFilePencil,
  IconGridDots,
  IconHash,
  IconHeart,
  IconHome,
  IconInfoSquare,
  IconLink,
  IconLock,
  IconLogin2,
  IconMail,
  IconMapPin,
  IconMenu2,
  IconMessageDots,
  IconNews,
  IconPaperclip,
  IconPhone,
  IconPlayerPlay,
  IconPlus,
  IconPower,
  IconPrinter,
  IconQuestionMark,
  IconReload,
  IconRss,
  IconSearch,
  IconSend,
  IconSettings,
  IconShare,
  IconSquare,
  IconTransfer,
  IconTrash,
  IconUpload,
  IconUser,
  IconVolume,
  IconVolumeOff,
  IconX,
} from '@tabler/icons-react';
import { Icon as UtrechtIcon } from '@utrecht/component-library-react';
import { forwardRef, PropsWithChildren } from 'react';
import { RijkshuisstijlIconID } from './IconTypes';

export const IconenSet: Partial<Record<RijkshuisstijlIconID, any>> = {
  activiteit: <IconCalendarCheck />,
  'agile-werken': <IconArrowIteration />,
  'api-inrichting': <IconApi />,
  audio: <IconVolume />,
  bel: <IconBell />,
  bewerken: <IconEdit />,
  blog: <IconFilePencil />,
  comment: <IconMessageDots />,
  communicatie: <IconBubble />,
  delen: <IconShare />,
  'delta-naar-links': <IconCaretLeft />,
  'delta-naar-rechts': <IconCaretRight />,
  'delta-omhoog': <IconCaretUp />,
  'delta-omlaag': <IconCaretDown />,
  'diagonale-pijl': <IconArrowUpRight />,
  downloaden: <IconDownload />,
  'externe-link': <IconExternalLink />,
  favoriet: <IconHeart />,
  'foto-vergroten': <IconArrowsDiagonal />,
  gegevensuitwisseling: <IconTransfer />,
  'geluid-aan': <IconVolume />,
  'geluid-uit': <IconVolumeOff />,
  'haakse-pijl': <IconCornerLeftUp />,
  hashtag: <IconHash />,
  home: <IconHome />,
  info: <IconInfoSquare />,
  inloggen: <IconLogin2 />,
  instellingen: <IconSettings />,
  'interne-link': <IconLink />,
  kalender: <IconCalendarCheck />,
  klok: <IconClock />,
  kruis: <IconX />,
  'let-op-met-loep': <IconAlertCircle />,
  'let-op': <IconAlertTriangle />,
  locatiemarker: <IconMapPin />,
  mail: <IconMail />,
  meer: <IconDotsVertical />,
  menu: <IconMenu2 />,
  nieuws: <IconNews />,
  paperclip: <IconPaperclip />,
  'permanent-beta': <IconBackhoe />,
  'pijl-naar-rechts': <IconArrowNarrowRight />,
  'pijl-naar-rechtsboven': <IconArrowUpRight />,
  'pijl-omhoog': <IconArrowNarrowUp />,
  'pijl-omlaag': <IconArrowNarrowDown />,
  plus: <IconPlus />,
  printer: <IconPrinter />,
  publicatie: <IconFile />,
  'rechte-pijl': <IconArrowNarrowUp />,
  refresh: <IconReload />,
  rss: <IconRss />,
  save: <IconDeviceFloppy />,
  'secure-link': <IconLock />,
  smartphone: <IconDeviceMobile />,
  tegelweergave: <IconGridDots />,
  telefoon: <IconPhone />,
  terug: <IconArrowNarrowLeft />,
  toegankelijkheid: <IconEye />,
  toelichting: <IconSquare />,
  'uit-aanknop': <IconPower />,
  upload: <IconUpload />,
  user: <IconUser />,
  versleutelen: <IconCloudLock />,
  verwijderen: <IconTrash />,
  verzenden: <IconSend />,
  video: <IconPlayerPlay />,
  vinkje: <IconCheck />,
  vraagteken: <IconQuestionMark />,
  zoek: <IconSearch />,
};

export const iconOptions = Object.keys(IconenSet);

export interface IconProps {
  icon?: any;
}

export const Icon = forwardRef(({ children, icon }: PropsWithChildren<IconProps>) => {
  return (
    <UtrechtIcon>
      {icon && IconenSet[icon as keyof typeof IconenSet]}
      {children}
    </UtrechtIcon>
  );
});

Icon.displayName = 'Icon';
